---
- name: install postgresql packages
  package: >-
    name={{ item }}
    state=installed
  with_items: "{{ postgresql_packages }}"
  register: postgresql_install_packages

- name: Get default PostgreSQL version
  environment:
    LC_ALL: 'C'
  shell: "apt-cache policy postgresql-client | grep -E '^\\s+Candidate:\\s+' | awk '{print $2}' | cut -d+ -f1"
  register: postgresql_apt_version
  changed_when: False

- name: create postgresql data path
  file: >-
    path={{ postgresql_data_directory }}
    state=directory
    owner=postgres
    group=postgres
    mode=0700

- name: initialize postgresql if necessary
  command: >-
    creates={{ postgresql_data_directory }}/PG_VERSION
    /usr/lib/postgresql/{{ postgresql_apt_version }}/bin/initdb
  notify: restart postgresql

- name: create postgresql backup path
  file: >-
    path={{ postgresql_backup_directory }}
    state=directory
    owner=postgres
    group=postgres
    mode=0700
